version: "3.8"

services:
  minio:
    container_name: minio-storage
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_storage:/data
    command: server --console-address ":9001" /data
  # postgres:
  #   networks:
  #     - node
  #   image: postgres:15.1
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: node
  redis:
    image: redis
    container_name: redis_node
    command: "redis-server --appendonly yes --requirepass qwerfvp.o654ijnQWE.RFVP654O.IJN --replica-read-only no"
    ports:
      - "6379:6379"
volumes:
  minio_storage:
