name: CI

on:
  push:
    branches: [master]

jobs:
  deploy-to-remote-server:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{secrets.SSH_PASSPHRASE}}
          port: 22
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            git fetch
            echo "fetched changes from git"
            git pull
            echo "pulled changes from git"
            npm i -legacy-peer-deps
            echo "reinstalled node modules"
            npm run build
            npm run rebuild
